// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const lexendDeca = localFont({
//   src: "./fonts/LexendDeca-Bold.ttf",
//   variable: "--font-lexend-deca",
//   weight: "100",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${lexendDeca.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import localFont from "next/font/local";
import "./globals.css";
import { Oregano, Livvic } from "next/font/google";

// Define the Geist Sans font
const geistSans = localFont({
  src: [
    {
      path: "./fonts/GeistVF.woff",
      weight: "100 900", // Specify the range of weights for Geist Sans
      style: "normal",
    },
  ],
});
const oregano = Oregano({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-oregano",
});
const livvic = Livvic({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-livvic",
});

// Define the Geist Mono font
const geistMono = localFont({
  src: [
    {
      path: "./fonts/GeistMonoVF.woff",
      weight: "100 900", // Specify the range of weights for Geist Mono
      style: "normal",
    },
  ],
});

// Define the Lexend Deca font with multiple weights and styles
const lexendDeca = localFont({
  src: [
    {
      path: "./fonts/LexendDeca-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/LexendDeca-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/LexendDeca-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/LexendDeca-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/LexendDeca-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

// Update the metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lexendDeca.variable} ${oregano.variable} ${livvic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
