import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Suspense } from "react"
import { useLoader } from "@react-three/fiber"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"

const Canvas = dynamic(() => import("@react-three/fiber").then((mod) => mod.Canvas), { ssr: false });
const OrbitControls = dynamic(() => import("@react-three/drei").then((mod) => mod.OrbitControls), { ssr: false });
const Environment = dynamic(() => import("@react-three/drei").then((mod) => mod.Environment), { ssr: false });

const Model = () => {
  const gltf = useLoader(GLTFLoader, "https://res.cloudinary.com/djsafovd9/image/upload/v1730176697/1BHK_005_f35sil.glb");
  return <primitive object={gltf.scene} scale={0.01} />;
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Three.js Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="globe">
        <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 0, 4], fov: 50 }}>
          <ambientLight intensity={0.7} />
          <spotLight intensity={0.5} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />
          <Suspense fallback={<div>Loading...</div>}>
            <Model />
            <Environment preset="city" />
          </Suspense>
          <OrbitControls autoRotate />
        </Canvas>
      </div>
    </div>
  )
}
